# Generated by Django 5.2.8 on 2026-01-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('invigilator', 'Invigilator'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
