# Generated by Django 5.2.8 on 2026-01-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('invigilator', 'Invigilator'), ('student', 'Student')], max_length=20, null=True),
        ),
    ]
