# Generated by Django 5.2.8 on 2026-01-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
