# Generated by Django 5.2.8 on 2026-01-30 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_studentexam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentexam',
            options={'verbose_name': 'Student Exam', 'verbose_name_plural': 'Student Exams'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
        migrations.CreateModel(
            name='InvigilatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.CharField(choices=[('chief', 'Chief Invigilator'), ('assistant', 'Assistant Invigilator')], max_length=20)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('invigilator', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.room')),
            ],
            options={
                'verbose_name': 'Invigilator Assignment',
                'verbose_name_plural': 'Invigilator Assignments',
                'ordering': ('exam', 'room', 'duty_type'),
                'unique_together': {('exam', 'room', 'duty_type'), ('invigilator', 'exam')},
            },
        ),
    ]
